# Generated by Django 3.2.20 on 2023-09-04 12:56

import api.validators
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(db_index=True, help_text='Enter the username', max_length=50, unique=True, validators=[api.validators.validate_username], verbose_name='Username')),
                ('email', models.EmailField(help_text='Enter the email', max_length=254, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(help_text='Enter your first name', max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Type your last name', max_length=50, verbose_name='Last Name')),
                ('password', models.TextField(help_text='The password must contain lowercase and uppercase letters and numbers', max_length=50, validators=[django.core.validators.MinLengthValidator(limit_value=6, message='The password must be more than 6 characters'), django.core.validators.MaxLengthValidator(limit_value=15, message='The password must be less than 15 characters'), api.validators.validate_password], verbose_name='Password')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
